name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Clone depot_tools
        run: |
          rm -rf depot_tools
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

      - name: Clone Chromium for iOS
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          rm -rf chromium
          mkdir chromium
          cd chromium
          fetch --no-history ios

      - name: Download Chromium for iOS build configurations
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          cd chromium/src
          pushd ios/build
          popd

      - name: Generate build directories
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          cd chromium/src
          brew install gnu-sed
          mkdir -p out/Release-iphoneos
          pushd out/Release-iphoneos
          rm -rf args.gn || true
          wget https://raw.githubusercontent.com/tigeryu8900/Chromium-for-iOS/main/args.gn
          gsed "s/API_KEY/$API_KEY/g" -i args.gn
          gsed "s/CLIENT_ID/$CLIENT_ID/g" -i args.gn
          gsed "s/CLIENT_SECRET/$CLIENT_SECRET/g" -i args.gn
          popd
          gn gen out/Release-iphoneos

      - name: Compile Chromium for iOS
        run: |
          export PATH="$(pwd)/depot_tools:$PATH"
          cd chromium/src
          autoninja -C out/Release-iphoneos gn_all

      - name: Prepare Chromium for iOS binaries for release
        run: |
          cd chromium/src
          pushd out/Release-iphoneos
          mkdir Payload
          mv Chromium.app Payload/
          7z a -tzip -mx=9 Chromium.ipa Payload
          mv Chromium.ipa ${{ github.workspace }}/Chromium.ipa
          popd

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.3.4
        with:
          name: Chromium.ipa
          path: ${{ github.workspace }}/Chromium.ipa
          if-no-files-found: error
